await_send = true
is_live = false

[src_pulsar]
hostname = ""
port = 6651
tenant = ""
namespace = ""
topics = [
    ""
]

[src_pulsar.oauth]
client_id = ""
client_secret = ""
client_email = ""
issuer_url = ""
audience = ""

[dest_pulsar]
hostname = ""
port = 6651
tenant = ""
namespace = ""
topics = [
    ""
]
token = ""

[dest_pulsar.oauth]
client_id = ""
client_secret = ""
client_email = ""
issuer_url = ""
audience = ""