await_send = true

[src_pulsar]
hostname = ""
port = 6651
tenant = ""
namespace = ""
topic = ""

[src_pulsar.oauth]
client_id = ""
client_secret = ""
client_email = ""
issuer_url = ""
audience = ""

[dest_pulsar]
hostname = ""
port = 6651
tenant = ""
namespace = ""
topic = ""
token = ""

[dest_pulsar.oauth]
client_id = ""
client_secret = ""
client_email = ""
issuer_url = ""
audience = ""